import React from "react";

import {
  AiOutlineHeart,
  AiOutlineMail,
  AiOutlineLock,
  AiOutlineUserAdd,
  AiOutlinePoweroff,
  AiFillPlayCircle,
  AiFillStepBackward,
  AiFillStepForward,
  AiOutlineSelect,
  AiFillPauseCircle,
  AiFillHeart,
} from "react-icons/ai";
import { BiPlayCircle, BiLike, BiMessageDetail } from "react-icons/bi";
import { BsGear, BsMusicNoteBeamed, BsPlayFill } from "react-icons/bs";
import {
  FaSistrix,
  FaTshirt,
  FaShoppingBag,
  FaUserCircle,
  FaRandom,
} from "react-icons/fa";
import { FiDownload, FiFolderPlus } from "react-icons/fi";
import {
  GiLinkedRings,
  GiExpand,
  GiSpeaker,
  GiSpeakerOff,
  GiMale,
  GiFemale,
} from "react-icons/gi";
import { HiOutlinePlus } from "react-icons/hi";
import { IoMdCheckmarkCircle } from "react-icons/io";
import {
  RiArrowDropRightFill,
  RiArrowDropDownFill,
  RiNeteaseCloudMusicLine,
  RiMedalLine,
  RiPlayList2Fill,
} from "react-icons/ri";
import { RiShareBoxFill } from "react-icons/ri";
import { TiThList, TiArrowLoop } from "react-icons/ti";
import {
  MdPause,
  MdHighQuality,
  MdNavigateNext,
  MdCancel,
} from "react-icons/md";
import {
  VscListSelection,
  VscChromeClose,
  VscListFlat,
  VscTrash,
  VscDebugStepBack,
} from "react-icons/vsc";

const icons = {
  arrowDown: <RiArrowDropDownFill className="icon" />,
  arrowRight: <RiArrowDropRightFill className="icon" />,
  back: <AiFillStepBackward className="icon" />,
  error: <MdCancel className="icon" />,
  done: <IoMdCheckmarkCircle className="icon" />,
  chain: <GiLinkedRings className="icon" />,
  close: <VscChromeClose className="icon" />,
  cloudMusic: <RiNeteaseCloudMusicLine className="icon" />,
  download: <FiDownload className="icon" />,
  exit: <AiOutlinePoweroff className="icon" />,
  expand: <GiExpand className="icon" />,
  fav: <AiOutlineHeart className="icon" />,
  favFill: <AiFillHeart className="icon" />,
  female: <GiFemale className="icon" />,
  folder: <FiFolderPlus className="icon" />,
  forward: <AiFillStepForward className="icon" />,
  gear: <BsGear className="icon" />,
  like: <BiLike className="icon" />,
  list: (
    <VscListSelection
      className="icon"
      style={{ transform: "rotateZ(-90deg)" }}
    />
  ),
  listFlat: <VscListFlat className="icon" />,
  listThick: <TiThList className="icon" />,
  lock: <AiOutlineLock className="icon" />,
  loopSingle: <VscDebugStepBack className="icon" />,
  loopList: <TiArrowLoop className="icon" />,
  loopRandom: <FaRandom className="icon" />,
  male: <GiMale className="icon" />,
  mail: <AiOutlineMail className="icon" />,
  medal: <RiMedalLine className="icon" />,
  message: <BiMessageDetail className="icon" />,
  music: <BsMusicNoteBeamed className="icon" />,
  next: <MdNavigateNext className="icon" />,
  pause: <AiFillPauseCircle className="icon" />,
  pauseLine: <MdPause className="icon" />,
  play: <BiPlayCircle className="icon" />,
  playing: <BsPlayFill className="icon" />,
  playFill: <AiFillPlayCircle className="icon" />,
  playList: <RiPlayList2Fill className="icon" />,
  plus: <HiOutlinePlus className="icon" />,
  quality: <MdHighQuality className="icon" />,
  search: <FaSistrix className="icon" />,
  share: <RiShareBoxFill className="icon" />,
  speaker: <GiSpeaker className="icon" />,
  speakerOff: <GiSpeakerOff className="icon" />,
  shop: <FaShoppingBag className="icon" />,
  theme: <FaTshirt className="icon" />,
  trash: <VscTrash className="icon" />,
  user: <AiOutlineUserAdd className="icon" />,
  userCircle: <FaUserCircle className="icon" />,
  zoomLeft: <AiOutlineSelect className="icon" />,
};

export default new Proxy(icons, {
  get(target, prop, reciver) {
    return prop in target
      ? Reflect.get(target, prop, reciver)
      : Reflect.get(target, "music", reciver);
  },
});

export const emojis = [
  "😀",
  "😁",
  "😂",
  "🤣",
  "😃",
  "😄",
  "😅",
  "😆",
  "😉",
  "😊",
  "😋",
  "😎",
  "😍",
  "😘",
  "😗",
  "😙",
  "😚",
  "🙂",
  "🤗",
  "🤩",
  "🤔",
  "🤨",
  "😐",
  "😑",
  "😶",
  "🙄",
  "😏",
  "😣",
  "😥",
  "😮",
  "🤐",
  "😯",
  "😪",
  "😫",
  "😴",
  "😌",
  "😛",
  "😜",
  "😝",
  "🤤",
  "😒",
  "😓",
  "😔",
  "😕",
  "🙃",
  "🤑",
  "😲",
  "☹",
  "🙁",
  "😖",
  "😞",
  "😟",
  "😤",
  "😢",
  "😭",
  "😦",
  "😧",
  "😨",
  "😩",
  "🤯",
  "😬",
  "😰",
  "😱",
  "😳",
  "🤪",
  "😵",
  "😡",
  "😠",
  "🤬",
  "😷",
  "🤒",
  "🤕",
  "🤢",
  "🤮",
  "🤧",
  "😇",
  "🤠",
  "🤡",
  "🤥",
  "🤫",
  "🤭",
  "🧐",
  "🤓",
  "😈",
  "👿",
  "👹",
  "👺",
  "💀",
  "👻",
  "👽",
  "🤖",
  "💩",
  "👦",
  "👶",
  "👧",
  "👨",
  "👩",
  "👴",
  "👵",
  "👾",
  "👮",
  "🕵",
  "💂",
  "👷",
  "🤴",
  "👸",
  "👳",
  "👲",
  "🧕",
  "🧔",
  "👱",
  "🤵",
  "👰",
  "🤰",
  "🤱",
  "👼",
  "🎅",
  "🤶",
  "🙍",
  "🙎",
  "🙅",
  "🙆",
  "💁",
  "🙋",
  "🙇",
  "🤦",
  "🤷",
  "💆",
  "💇",
  "🚶",
  "🏃",
  "💃",
  "🕺",
  "👯",
  "🕴",
  "🗣",
  "👤",
  "👥",
  "👫",
  "👬",
  "👭",
  "💏",
  "💑",
  "👪",
];
